<%@ Page Language="C#" AutoEventWireup="true" CodeFile="view.aspx.cs" Inherits="Admin_view" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<title> SA Times </title>
<link rel="stylesheet" href="css/bootstrap.min.css"/>
<link rel="stylesheet" href="css/custom.css"/>
<link rel="stylesheet" href="css/sidebar.css"/>
<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/sidebarjs.js"></script>
<link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="../ckeditor/ckeditor.js"></script>
    <script src="../ckeditor/ckeditor.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
</head>
  

  
<form id="form2" runat="server">
   
<div id="top-nav" class="navbar navbar-inverse navbar-static-top box-shadow">
    <div class="container-fluid" >
        <div class="navbar-header" >
          
           
            <asp:Label ID="Label1" runat="server" BackColor="White" ForeColor="#990000" Font-Size="Medium"></asp:Label>
          
           
        </div>
        <div class="navbar-collapse collapse">
            
        </div>
    </div>
    <!-- /container -->
</div>
<!-- /Header -->
<!-- Main -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            <!-- Left column -->
            <img src="../img/bg-img/sa_logo.gif" height="85px" />
            <hr>


            <ul class="nav nav-stacked">
                    <ul class="nav nav-stacked collapse" id="menu">
                   
                    </ul>
                </li>
            

               
				<li class="nav-header">

				
                    <a href="#" data-toggle="collapse" data-target="#menu3"><strong> SA times </strong> <i class="glyphicon glyphicon-chevron-down pull-right"></i></a>
                    <ul class="nav nav-stacked collapse" id="menu3">
                        <li><a href="add.aspx"><i class="glyphicon glyphicon-circle"></i> Create New  </a></li>
                        <li><a href="view.aspx"><i class="glyphicon glyphicon-circle"></i> View </a></li>
                         <li><a href="edit.aspx"><i class="glyphicon glyphicon-circle"></i> Update</a></li>
                        <li><a href=""><i class="glyphicon glyphicon-circle"></i> 

                            </a></li>
                    </ul>
                </li>
				
				   <hr>
				
	
		
				
            </ul>


          
        </div>
        <!-- /col-3 -->
        <div class="col-sm-9 border-left">

         
			
			
           
            <div class="row">
                <!-- center left-->
                <div class="col-md-6">
           
              
                   
<!--
      
  


  </div>
  
        </div>
          <br>      <!--/col-span-6-->

                
            </div>
            <!--/row-->

    <!--grid data -->
<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#999999" BorderStyle="None" 
    cssclass="table table-bordered table-condensed table-hover table-responsive"
    BorderWidth="1px" CellPadding="3" DataSourceID="SqlDataSource1" GridLines="Vertical" Height="155px" Width="992px" AutoGenerateDeleteButton="True" DataKeyNames="post_id" OnRowDeleted="Page_Load" OnRowEditing="Page_Load" AllowPaging="True" PageSize="8" OnSelectedIndexChanged="GridView1_SelectedIndexChanged1">
        <AlternatingRowStyle BackColor="Gainsboro" />
        <Columns>
            <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" >
            <ControlStyle Font-Bold="False" Font-Size="Medium" />
            <HeaderStyle BackColor="#FFFFCC" BorderColor="#FFCC99" ForeColor="#006699" />
            </asp:BoundField>
            <asp:TemplateField HeaderText="file_name" SortExpression="file_name" >
                <EditItemTemplate>
                    <asp:TextBox ID="TextBox1" runat="server"  Text='<%# Bind("file_name") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Image ID="Image2" runat="server" Height="104px" ImageUrl='<%# Eval("file_name") %>' Width="177px" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="post_id" HeaderText="ID" ReadOnly="True" SortExpression="post_id" />
        </Columns>
        <EmptyDataTemplate>
            <asp:Image ID="Image1" runat="server" ImageUrl='<%# Eval("file_name") %>' Width="139px" />
        </EmptyDataTemplate>
        <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
        <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
        <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#0000A9" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#000065" />
    </asp:GridView>


        <!--grid data -->
        </div>
        <!--/col-span-9-->
    </div>
</div>
<!-- /Main -->


<div class="modal" id="addWidgetModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Add Widget</h4>
            </div>
            <div class="modal-body">
                <p>Add a widget stuff here..</p>
            </div>
            <div class="modal-footer">
                <a href="#" data-dismiss="modal" class="btn">Close</a>
                <a href="#" class="btn btn-primary">Save changes</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dalog -->
</div>
        </div>
<!-- /.modal -->
   <script src="js/jquery.min.js"></script>
   <script src="js/bootstrap.min.js"></script>
	</form>
       
          </body>
      


    
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:sareAamConnectionString %>" SelectCommand="SELECT [Title], [file_name], [post_id] FROM [post]" DeleteCommand="DELETE FROM [post] WHERE [post_id] = @original_post_id" InsertCommand="INSERT INTO [post] ([Title], [file_name]) VALUES (@Title, @file_name)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [post] SET [Title] = @Title, [file_name] = @file_name WHERE [post_id] = @original_post_id">
        <DeleteParameters>
            <asp:Parameter Name="original_post_id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Title" Type="String" />
            <asp:Parameter Name="file_name" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Title" Type="String" />
            <asp:Parameter Name="file_name" Type="String" />
            <asp:Parameter Name="original_post_id" Type="Int32" />
        </UpdateParameters>
</asp:SqlDataSource>
        </form>

  

      


</html>

